#!/bin/sh
if [ -z "$OFv2412_SOURCED" ]; then
    export OFv2412_SOURCED=1

    echo "Sourcing OFv2412..."
    . ~/OpenFOAM/OpenFOAM-v2412/etc/bashrc         # Sourcing OpenFOAM-v2412

fi
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

keepCases="
mesh_80_Co_0.1
"

loseCases="
mesh_80_Co_0.01
mesh_160_Co_0.01
"

for caseName in $keepCases
do
    (cd "$caseName" && foamCleanTutorials)
done

for caseName in $loseCases
do
    removeCase "$caseName"
done

echo "Removing Bubble_PostProcessing/Figures"
rm -r Bubble_PostProcessing/Figures
rm Bubble_PostProcessing/log.postProcessing

#------------------------------------------------------------------------------
