#!/bin/sh
if [ -z "$OFv2412_SOURCED" ]; then
    export OFv2412_SOURCED=1

    echo "Sourcing OFv2412..."
    . ~/OpenFOAM/OpenFOAM-v2412/etc/bashrc         # Sourcing OpenFOAM-v2412

fi
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cases="
mesh_80_Co_0.01
mesh_160_Co_0.01
"

setMaxCoSmaller()
{
    sed -i "s/maxCo           0.1;/maxCo           0.01;/" "$1/system/controlDict"
}

setMeshFiner()
{
    sed -i "s/80 160/160 320/" "$1/system/blockMeshDict"
}

runSimulation()
{
    runApplication blockMesh
    runApplication setFields
    runApplication decomposePar
    runParallel $(getApplication)
    runApplication reconstructPar
}

postProcess()
{
    cd Bubble_PostProcessing
    mkdir Figures
    echo "Running PostProcessing.py"
    python PostProcessing.py > log.postProcessing 2>&1
    cd ..
}

# Do mesh_80_Co_0.1
(cd mesh_80_Co_0.1 && foamRunTutorials && touch mesh_80_Co_0.1.foam)

for acase in $cases
do
    cloneCase mesh_80_Co_0.1 "$acase"
    case "$acase" in
    mesh_80_Co_0.01)
	setMaxCoSmaller "$acase"
	;;

    mesh_160_Co_0.01)
        setMeshFiner "$acase"
	setMaxCoSmaller "$acase"
	;;
    esac
    ( cd $acase || exit
    restore0Dir
    runSimulation
    touch "$acase.foam"
    )
done

# Post_process

postProcess

<<com
if notTest "$@"
then
    # Clone case
    cloneCase mesh_80_Co_0.1 mesh_80_Co_0.01

    (
        cd mesh_80_Co_0.01 || exit

        # Modify case
        setMaxCoSmaller
	restore0Dir

        # And execute
	runSimulation
    )

    # Clone case
    cloneCase mesh_80_Co_0.01 mesh_160_Co_0.01

    (
        cd mesh_160_Co_0.01 || exit

        # Modify case
        setMeshFiner
	restore0Dir

        # And execute
	runSimulation
    )
fi
com
#------------------------------------------------------------------------------
